spring:
  datasource:
    url: jdbc:postgresql://produto-db:5432/produto_db
    username: produto
    password: produto
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8082