server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-estoque:5432/estoques
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
