server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-cliente:5432/clientes
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true